version: '3'
services:
  postfix-server:
    build:
      context: .
    environment:
      - POSTFIX_MYHOSTNAME=no-reply.bitendian.com
      - POSTFIX_MYDESTINATION=localhost
      - POSTFIX_MYDOMAIN=bitendian.com
    container_name: 'bitendian-postfix-server'